on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-git-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout
      - name: source-version
        id: source-version
        run: |
          echo "::set-output name=version::$(cat version)"
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: push-container-image
        with:
          image: go-git-workflows #todo rename to git-workflows
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GHCR_TOKEN }}
          dockerfile: Containerfile
          directory:  .
          addLatest: true
          tags: ${{ steps.source-version.outputs.version }},latest
          buildArgs: VERSION="${{ steps.source-version.outputs.version }}"
#  notify: todo enable
#    name: Slack Notifications
#    runs-on: ubuntu-latest
#    if: ${{ failure() }}
#    needs:
#      - build-git-workflows
#    steps:
#      - name: Notify Slack channel on failure
#        uses: rtCamp/action-slack-notify@v2
#        env:
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#          SLACK_ICON: https://avatars.githubusercontent.com/u/74975412?s=200&v=4
#          SLACK_USERNAME: ${{ github.repository }}
#          SLACK_COLOR: '#ff0033'
#          SLACK_FOOTER: ''